### ISSUE TITLE
Create contributing.md with standarts 

### ISSUE THREAD

**Issue by Math-O5** [tomieiro/std-moon#10]
Criar um arquivo para contribuidores.

Esse arquivo conterá:

Instruções de como contribuir em copiar e clonar o repositório;
Padrão para fazer o pull request e uma estimativa de resposta;
O que se espera na mensagem de commit;

Padrões para criar novos features e bugs (por contribuidores externos);
Como devem ser escritos;
Tempo estimado para responder a novos issues;

**Comment by Math-O5** [comment]
@matheustomieiro Me mandando a estimativa de tempo de resposta(uma semana,  talvez?), posso enviar o texto inicial.

**Comment by tomieiro** [comment]
@Math-O5 Aproximadamente uma semana.
