### ISSUE TITLE
Implementar djikstra

### ISSUE THREAD

**Issue by tomieiro** [tomieiro/std-moon#33]

**Comment by shawnjb** [comment]
Implementé estas características en la nueva solicitud de extracción que creé.

**Comment by AnaClaraAmorim** [comment]
Gostaria de trabalhar nessa tarefa. Ana Clara (aluna USP open source)

**Comment by tomieiro** [comment]
> Gostaria de trabalhar nessa tarefa. Ana Clara (aluna USP open source)

Assigned!
