### ISSUE TITLE
Implementar quick sort

### ISSUE THREAD

**Issue by tomieiro** [tomieiro/std-moon#35]

**Comment by FulecoRafa** [comment]
Gostaria de trabalhar nesta issue (aluno USP Open Source)

**Comment by tomieiro** [comment]
> Gostaria de trabalhar nesta issue (aluno USP Open Source)

Essa foi já foi feita, está em pull request, só não fechou ainda pois está em revisão 😅 ...

**Comment by FulecoRafa** [comment]
Tranquilo
Grato pela oportunidade
