### ISSUE TITLE
Implementar merge sort

### ISSUE THREAD

**Issue by tomieiro** [tomieiro/std-moon#36]

**Comment by FulecoRafa** [comment]
Gostaria de trabalhar nesta issue (aluno USP Open Source)

**Comment by tomieiro** [comment]
> Gostaria de trabalhar nesta issue (aluno USP Open Source)

Olá, Rafael. Assigned!

**Comment by ghost** [comment]
Implementé estas características en la nueva solicitud de extracción que creé.

**Comment by tomieiro** [comment]
> Implementé estas características en la nueva solicitud de extracción que creé.

Sorry, @shawnjb, but @FulecoRafa already had implemented, it's on review for PR.

**Comment by ghost** [comment]
Sounds fine to me, I'm just glad it was done.
