### ISSUE TITLE
Implementar insertion sort

### ISSUE THREAD

**Issue by tomieiro** [tomieiro/std-moon#37]
@XDyao Poderia implementar, por favor?

**Comment by XDyao** [comment]
> @XDyao Poderia implementar, por favor?

Irei realizar esta Issue.

**Comment by ghost** [comment]
What is insertion sorting? What is this supposed to mean?

I'd assume you're talking about sorting it by alphabetical order, numerical order or etc?

**Comment by tomieiro** [comment]
> What is insertion sorting? What is this supposed to mean?
> 
> I'd assume you're talking about sorting it by alphabetical order, numerical order or etc?

Hi. Insertion sort algorithm basically compares an element in array with all previous elements in a for loop (and eventually swaps if this element is smaller). And that's it, it produces an sorted array in numeric/alphabetic/etc order as output. It's good enough in small arrays scenario and when compared with other N² algorithms.

Wikipedia shows a gif that illustrates that! It's quite nice :)

https://en.wikipedia.org/wiki/Insertion_sort#%3A%7E%3Atext%3DInsertion_sort_is_a_simple%2C%2C_heapsort%2C_or_merge_sort.?wprov=sfla1

**Comment by ghost** [comment]
I'll be able to make a solution today.

**Comment by tomieiro** [comment]
> I'll be able to make a solution today.

Nice! I assigned to you too. Take your time :)

**Comment by ghost** [comment]
I created a repository regarding different algorithms, so far I have bubble sorting & insertion sorting in the module.

[You can see the module here.](https://github.com/obtusity/algorithms/blob/master/modules/algorithms.lua)
